site_name: 0221 — Muntatge i Manteniment d’Equips
site_description: Publicació progressiva des d'un sol repositori
site_url: https://jpardo20.github.io/mme-apunts/

nav:
  - Inici: index.md
  - Continguts: continguts.md

theme:
  name: material
  language: ca
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy

extra_css:
  - assets/styles.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
